project_structure:
    build: client/src/artifacts
    tests: scripts/brownie/tests
    scripts: scripts/brownie
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'

# automatically fetch contract sources from Etherscan
autofetch_sources: true
dev_deployment_artifacts: true

